import { useCallback, useEffect, useState } from 'react';
import {
  AlertOutlined,
  CheckCircleOutlined,
  DeleteOutlined,
  ExclamationCircleOutlined,
  FileSearchOutlined,
  PlusOutlined,
  ReloadOutlined,
  ToolOutlined,
} from '@ant-design/icons';
import {
  Badge,
  Button,
  Card,
  Checkbox,
  Col,
  Drawer,
  Form,
  Input,
  message,
  Modal,
  Popconfirm,
  Row,
  Select,
  Space,
  Switch,
  Table,
  Tag,
  Tooltip,
  Typography,
} from 'antd';
import type { ColumnsType } from 'antd/es/table';
import {
  acknowledgeAlert,
  acknowledgeAlerts,
  createAlertRule,
  deleteAlertRule,
  deleteAlert,
  fetchAlertRules,
  fetchAlerts,
  updateAlertRule,
  type AlertRuleRow,
  type LogAlertRow,
} from '@/api/logs';
import { EmptyState } from '@/components/common/EmptyState';
import { ErrorState } from '@/components/common/ErrorState';
import { PageSkeleton } from '@/components/common/PageSkeleton';
import {
  LOG_FACILITY_LABEL,
  LOG_SEVERITY_COLOR,
  LOG_SEVERITY_LABEL,
  LOG_SEVERITY_ORDER,
  type LogFacility,
  type LogSeverity,
} from '@/types/log';

const SEVERITY_OPTIONS = LOG_SEVERITY_ORDER.map((value) => ({
  value,
  label: LOG_SEVERITY_LABEL[value],
}));

const FACILITY_OPTIONS = Object.entries(LOG_FACILITY_LABEL)
  .filter(([key]) => key !== 'UNKNOWN')
  .map(([value, label]) => ({ value, label }));

function formatTimestamp(value: string): string {
  try {
    return new Date(value).toLocaleString(undefined, {
      month: 'short',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });
  } catch {
    return value;
  }
}

const RULE_PRESETS = [
  {
    name: 'Config change detected',
    description: 'Fire when anyone commits a config change',
    minSeverity: 'NOTICE' as LogSeverity,
    messagePattern: '(commit performed|configuration change)',
    facility: 'CHANGE_LOG',
  },
  {
    name: 'Interface went down',
    description: 'Fire on link DOWN trap',
    minSeverity: 'WARNING' as LogSeverity,
    messagePattern: '(LINK_DOWN|SNMP_TRAP.*DOWN)',
    facility: 'DAEMON',
  },
  {
    name: 'Login from new source',
    description: 'Fire on successful user login',
    minSeverity: 'NOTICE' as LogSeverity,
    messagePattern: '(login successful|UI_LOGIN_EVENT)',
    facility: 'AUTHORIZATION',
  },
  {
    name: 'Critical error on device',
    description: 'Fire on any ERROR or higher from any program',
    minSeverity: 'ERROR' as LogSeverity,
    messagePattern: '',
    facility: '',
  },
];

// ── Rules panel ────────────────────────────────────────────────────────────────

function RuleCard({ rule, onUpdate, onDelete }: {
  rule: AlertRuleRow;
  onUpdate: (id: string, patch: Partial<AlertRuleRow>) => void;
  onDelete: (id: string) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [form] = Form.useForm();

  const handleSave = async () => {
    try {
      const vals = await form.validateFields();
      await updateAlertRule(rule.id, vals);
      message.success('Rule updated');
      setEditing(false);
      onUpdate(rule.id, vals);
    } catch (e) {
      /* form validation shown inline */
    }
  };

  return (
    <Card
      size="small"
      style={{ marginBottom: 8 }}
      extra={
        <Space size={4}>
          <Switch
            size="small"
            checked={rule.enabled}
            onChange={(checked) => {
              void updateAlertRule(rule.id, { enabled: checked }).then(() => {
                onUpdate(rule.id, { enabled: checked });
              });
            }}
          />
          <Button size="small" icon={<ToolOutlined />} onClick={() => setEditing(true)} />
          <Popconfirm
            title="Delete this rule?"
            description="All alerts generated by this rule will also be deleted."
            onConfirm={() => {
              void deleteAlertRule(rule.id).then(() => {
                onDelete(rule.id);
              });
            }}
          >
            <Button size="small" danger icon={<DeleteOutlined />} />
          </Popconfirm>
        </Space>
      }
    >
      <Typography.Text strong>{rule.name}</Typography.Text>
      {rule.description && (
        <Typography.Paragraph type="secondary" style={{ marginBottom: 4, fontSize: 12 }}>
          {rule.description}
        </Typography.Paragraph>
      )}
      <Space size={4} wrap>
        <Tag color={LOG_SEVERITY_COLOR[rule.minSeverity]}>
          {LOG_SEVERITY_LABEL[rule.minSeverity]}
        </Tag>
        {rule.facility && (
          <Tag>{LOG_FACILITY_LABEL[rule.facility as LogFacility] ?? rule.facility}</Tag>
        )}
        {rule.messagePattern && (
          <Typography.Text type="secondary" style={{ fontFamily: 'monospace', fontSize: 11 }}>
            /{rule.messagePattern}/
          </Typography.Text>
        )}
        {rule.unacknowledgedCount > 0 && (
          <Badge count={rule.unacknowledgedCount} style={{ backgroundColor: '#1677ff' }} />
        )}
      </Space>

      <Modal
        title={`Edit rule: ${rule.name}`}
        open={editing}
        onCancel={() => setEditing(false)}
        onOk={handleSave}
        okText="Save"
      >
        <Form
          form={form}
          layout="vertical"
          initialValues={{
            name: rule.name,
            description: rule.description ?? '',
            minSeverity: rule.minSeverity,
            messagePattern: rule.messagePattern ?? '',
            facility: rule.facility ?? '',
          }}
        >
          <Form.Item name="name" label="Rule name" rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="description" label="Description">
            <Input />
          </Form.Item>
          <Form.Item name="minSeverity" label="Minimum severity" rules={[{ required: true }]}>
            <Select options={SEVERITY_OPTIONS} />
          </Form.Item>
          <Form.Item name="facility" label="Facility filter (optional)">
            <Select
              allowClear
              placeholder="Any facility"
              options={[{ value: '', label: 'Any facility' }, ...FACILITY_OPTIONS]}
            />
          </Form.Item>
          <Form.Item
            name="messagePattern"
            label="Message pattern (regex, optional)"
            extra="Leave blank to match all messages at or above the minimum severity."
          >
            <Input placeholder="e.g. LINK_DOWN|commit performed" />
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  );
}

function NewRuleDrawer({ open, onClose, onCreated }: {
  open: boolean;
  onClose: () => void;
  onCreated: (rule: AlertRuleRow) => void;
}) {
  const [form] = Form.useForm();
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async () => {
    try {
      const vals = await form.validateFields();
      setSubmitting(true);
      const { rule } = await createAlertRule({
        name: vals.name,
        description: vals.description || undefined,
        minSeverity: vals.minSeverity,
        messagePattern: vals.messagePattern || undefined,
        facility: vals.facility || undefined,
      });
      message.success(`Rule "${rule.name}" created`);
      form.resetFields();
      onClose();
      onCreated(rule);
    } catch {
      /* validation shown inline */
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Drawer
      title="New alert rule"
      placement="right"
      width={420}
      open={open}
      onClose={onClose}
      extra={
        <Button type="primary" loading={submitting} onClick={handleSubmit}>
          Create rule
        </Button>
      }
    >
      <Form form={form} layout="vertical">
        <Form.Item name="name" label="Rule name" rules={[{ required: true }]}>
          <Input placeholder="e.g. Config changes on core switches" />
        </Form.Item>
        <Form.Item name="description" label="Description (optional)">
          <Input.TextArea placeholder="What this rule watches for..." rows={2} />
        </Form.Item>
        <Form.Item name="minSeverity" label="Minimum severity" rules={[{ required: true }]}
          extra="Alerts fire for logs at or above this severity.">
          <Select options={SEVERITY_OPTIONS} />
        </Form.Item>
        <Form.Item name="facility" label="Facility filter (optional)">
          <Select allowClear placeholder="Any facility" options={FACILITY_OPTIONS} />
        </Form.Item>
        <Form.Item
          name="messagePattern"
          label="Message pattern (regex, optional)"
          extra={
            <span>
              Leave blank to match all messages at or above the minimum severity.
              Test your regex at{' '}
              <a href="https://regex101.com" target="_blank" rel="noopener noreferrer">
                regex101.com
              </a>
              .
            </span>
          }
        >
          <Input placeholder="e.g. commit performed|LINK_DOWN" />
        </Form.Item>
      </Form>

      <Typography.Text strong style={{ display: 'block', marginBottom: 8 }}>
        Quick presets
      </Typography.Text>
      <Space wrap size={4}>
        {RULE_PRESETS.map((preset) => (
          <Button
            key={preset.name}
            size="small"
            onClick={() => {
              form.setFieldsValue({
                name: preset.name,
                description: preset.description,
                minSeverity: preset.minSeverity,
                messagePattern: preset.messagePattern,
                facility: preset.facility || undefined,
              });
            }}
          >
            {preset.name}
          </Button>
        ))}
      </Space>
    </Drawer>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export function AlertsPage() {
  const [alertRules, setAlertRules] = useState<AlertRuleRow[]>([]);
  const [alerts, setAlerts] = useState<LogAlertRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const [showNewRule, setShowNewRule] = useState(false);
  const [selectedRowKeys, setSelectedRowKeys] = useState<string[]>([]);
  const [showAcknowledged, setShowAcknowledged] = useState(false);
  const [tab, setTab] = useState<'alerts' | 'rules'>('alerts');

  const loadRules = useCallback(async () => {
    try {
      const { rules } = await fetchAlertRules(true);
      setAlertRules(rules);
    } catch (e) {
      console.error('[alerts] load rules failed', e);
    }
  }, []);

  const loadAlerts = useCallback(async () => {
    try {
      const { alerts: rows } = await fetchAlerts({
        acknowledged: showAcknowledged ? undefined : false,
        limit: 200,
      });
      setAlerts(rows);
    } catch (e) {
      console.error('[alerts] load alerts failed', e);
    }
  }, [showAcknowledged]);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      await Promise.all([loadRules(), loadAlerts()]);
    } catch (e) {
      setError(e instanceof Error ? e : new Error('Failed to load'));
    } finally {
      setLoading(false);
    }
  }, [loadRules, loadAlerts]);

  useEffect(() => {
    void load();
  }, [load]);

  const handleAcknowledge = async (id: string) => {
    await acknowledgeAlert(id);
    setAlerts((prev) => prev.map((a) => (a.id === id ? { ...a, acknowledged: true } : a)));
    setAlertRules((prev) =>
      prev.map((r) => {
        if (r.unacknowledgedCount <= 0) return r;
        return { ...r, unacknowledgedCount: r.unacknowledgedCount - 1 };
      }),
    );
    setSelectedRowKeys((prev) => prev.filter((k) => k !== id));
    message.success('Alert acknowledged');
  };

  const handleAcknowledgeSelected = async () => {
    if (!selectedRowKeys.length) return;
    const count = (await acknowledgeAlerts(selectedRowKeys)).acknowledged;
    setAlerts((prev) =>
      prev.map((a) =>
        selectedRowKeys.includes(a.id) ? { ...a, acknowledged: true } : a,
      ),
    );
    setSelectedRowKeys([]);
    void loadRules();
    message.success(`${count} alert(s) acknowledged`);
  };

  const handleDeleteAlert = async (id: string) => {
    await deleteAlert(id);
    setAlerts((prev) => prev.filter((a) => a.id !== id));
  };

  const handleRuleDelete = async (id: string) => {
    setAlertRules((prev) => prev.filter((r) => r.id !== id));
    void loadAlerts(); // alerts may be gone
  };

  const handleRuleUpdate = async (id: string, patch: Partial<AlertRuleRow>) => {
    setAlertRules((prev) => prev.map((r) => (r.id === id ? { ...r, ...patch } : r)));
  };

  const handleRuleCreated = (rule: AlertRuleRow) => {
    setAlertRules((prev) => [...prev, rule]);
  };

  const columns: ColumnsType<LogAlertRow> = [
    {
      title: '',
      dataIndex: 'acknowledged',
      width: 40,
      render: (ack: boolean) =>
        ack ? (
          <CheckCircleOutlined style={{ color: '#52c41a' }} />
        ) : (
          <ExclamationCircleOutlined style={{ color: '#ff4d4f' }} />
        ),
    },
    {
      title: 'Time',
      dataIndex: 'timestamp',
      width: 160,
      render: formatTimestamp,
    },
    {
      title: 'Severity',
      dataIndex: 'severity',
      width: 100,
      render: (v: LogSeverity) => (
        <Tag color={LOG_SEVERITY_COLOR[v]}>{LOG_SEVERITY_LABEL[v]}</Tag>
      ),
    },
    {
      title: 'Rule',
      dataIndex: 'ruleName',
      width: 180,
      ellipsis: true,
    },
    {
      title: 'Device / Host',
      dataIndex: 'hostname',
      width: 160,
      render: (h: string, row) =>
        row.deviceId ? (
          <span>
            {h}
            <Typography.Text type="secondary" style={{ fontSize: 11, marginLeft: 6 }}>
              {row.deviceIp}
            </Typography.Text>
          </span>
        ) : (
          h
        ),
    },
    {
      title: 'Program',
      dataIndex: 'program',
      width: 110,
      render: (v: string | null) =>
        v ? <Tag style={{ fontFamily: 'monospace' }}>{v}</Tag> : '—',
    },
    {
      title: 'Message',
      dataIndex: 'message',
      ellipsis: true,
      render: (v: string) => (
        <Tooltip title={v}>
          <Typography.Text style={{ fontFamily: 'monospace', fontSize: 12 }}>{v}</Typography.Text>
        </Tooltip>
      ),
    },
    {
      title: '',
      key: 'actions',
      width: 100,
      render: (_v, row) => (
        <Space size={4}>
          {!row.acknowledged && (
            <Tooltip title="Acknowledge">
              <Button
                size="small"
                type="text"
                icon={<CheckCircleOutlined />}
                onClick={() => void handleAcknowledge(row.id)}
              />
            </Tooltip>
          )}
          <Popconfirm
            title="Delete this alert?"
            onConfirm={() => void handleDeleteAlert(row.id)}
          >
            <Button size="small" type="text" danger icon={<DeleteOutlined />} />
          </Popconfirm>
        </Space>
      ),
    },
  ];

  if (loading && !alertRules.length && !alerts.length) {
    return <PageSkeleton />;
  }
  if (error && !alertRules.length) {
    return <ErrorState title="Could not load alerts" error={error} onRetry={() => void load()} />;
  }

  const unackCount = alertRules.reduce((sum, r) => sum + r.unacknowledgedCount, 0);

  return (
    <div className="nc-page">
      <Row gutter={16} style={{ marginBottom: 16 }}>
        <Col span={24}>
          <Space>
            <Button
              type={tab === 'alerts' ? 'primary' : 'default'}
              icon={<AlertOutlined />}
              onClick={() => setTab('alerts')}
            >
              Alerts
              {unackCount > 0 && (
                <Badge count={unackCount} size="small" style={{ marginLeft: 8 }} />
              )}
            </Button>
            <Button
              type={tab === 'rules' ? 'primary' : 'default'}
              icon={<FileSearchOutlined />}
              onClick={() => setTab('rules')}
            >
              Rules
            </Button>
            <Button icon={<ReloadOutlined />} onClick={() => void load()}>
              Reload
            </Button>
          </Space>
        </Col>
      </Row>

      {tab === 'rules' ? (
        <div>
          <Row gutter={16} align="middle" style={{ marginBottom: 16 }}>
            <Col flex="auto">
              <Typography.Paragraph type="secondary" style={{ margin: 0 }}>
                {alertRules.length} rule{alertRules.length !== 1 ? 's' : ''} — alerts fire when a
                matching log entry arrives and are deduplicated within a 60-second window per device.
              </Typography.Paragraph>
            </Col>
            <Col>
              <Button type="primary" icon={<PlusOutlined />} onClick={() => setShowNewRule(true)}>
                New rule
              </Button>
            </Col>
          </Row>

          {alertRules.length === 0 ? (
            <EmptyState
              title="No alert rules yet"
              description="Create a rule to get notified when important events happen on your devices."
              extra={
                <Button type="primary" icon={<PlusOutlined />} onClick={() => setShowNewRule(true)}>
                  Create first rule
                </Button>
              }
            />
          ) : (
            alertRules.map((rule) => (
              <RuleCard
                key={rule.id}
                rule={rule}
                onUpdate={handleRuleUpdate}
                onDelete={handleRuleDelete}
              />
            ))
          )}

          <NewRuleDrawer
            open={showNewRule}
            onClose={() => setShowNewRule(false)}
            onCreated={handleRuleCreated}
          />
        </div>
      ) : (
        <div>
          <Row gutter={16} align="middle" style={{ marginBottom: 12 }}>
            <Col flex="auto">
              <Space>
                <Checkbox
                  checked={showAcknowledged}
                  onChange={(e) => setShowAcknowledged(e.target.checked)}
                >
                  Show acknowledged
                </Checkbox>
                {selectedRowKeys.length > 0 && (
                  <Button
                    size="small"
                    icon={<CheckCircleOutlined />}
                    onClick={() => void handleAcknowledgeSelected()}
                  >
                    Acknowledge selected ({selectedRowKeys.length})
                  </Button>
                )}
              </Space>
            </Col>
            <Col>
              <Typography.Text type="secondary">
                {alerts.length} alert{alerts.length !== 1 ? 's' : ''} shown
              </Typography.Text>
            </Col>
          </Row>

          <Table
            rowKey="id"
            size="small"
            dataSource={alerts}
            columns={columns}
            rowSelection={{
              selectedRowKeys,
              onChange: (keys) => setSelectedRowKeys(keys.map(String)),
            }}
            pagination={{ pageSize: 50 }}
            scroll={{ x: 900 }}
            locale={{
              emptyText: (
                <EmptyState
                  title="No alerts"
                  description="No alerts match the current filter. Alerts appear here when a rule matches a log entry."
                  extra={
                    <Button icon={<FileSearchOutlined />} onClick={() => setTab('rules')}>
                      Manage rules
                    </Button>
                  }
                />
              ),
            }}
          />
        </div>
      )}
    </div>
  );
}
