/**
 * Type definitions for the AI Assistant.
 *
 * The LLM (gpt-4.1-mini) is stateless — every request re-sends the
 * full message history. We mirror OpenAI's Chat Completions shape so
 * the wire format stays simple, then add a thin wrapper for the
 * NetConsole-specific bits (confirmation_required, tool role).
 */

import type { ChatCompletionMessageParam } from 'openai/resources/chat/completions';

/** Re-export of OpenAI's message shape for clarity. */
export type AssistantMessage = ChatCompletionMessageParam;

/**
 * A `tool` role message paired with its parent `assistant` tool_call.
 * The OpenAI wire format stores the tool_call_id only on the result
 * row; we keep the name too so the frontend can render the call
 * without re-parsing the assistant message.
 */
export type AssistantToolMessage = Extract<AssistantMessage, { role: 'tool' }>;

/** Anything that the LLM can call. */
export type AssistantToolName =
  // READ — devices + inventory
  | 'lookup_mac'
  | 'get_device'
  | 'get_device_interfaces'
  | 'list_devices'
  | 'list_dhcp_leases'
  | 'get_dhcp_pool_status'
  | 'list_dhcp_subnets'
  | 'get_dhcp_subnet'
  | 'get_fabric_topology'
  | 'search_recent_jobs'
  | 'get_job_detail'
  | 'get_recent_logs'
  | 'get_unacknowledged_alerts'
  | 'list_alert_rules'
  | 'list_users'
  | 'get_config_history'
  | 'get_config_diff'
  | 'list_discovery_scans'
  | 'get_discovery_scan'
  | 'get_netconsole_info'
  // WRITE — emit confirmation_required
  | 'queue_interface_action'
  | 'queue_log_collect'
  | 'queue_managed_check'
  | 'queue_apply_config'
  | 'queue_rollback_config'
  | 'apply_config_dry_run'
  | 'create_device'
  | 'update_device'
  | 'delete_device'
  | 'set_device_status'
  | 'queue_collect'
  | 'add_dhcp_reservation'
  | 'delete_dhcp_lease'
  | 'fix_static_reservation'
  | 'wipe_dhcp_subnet'
  | 'add_dhcp_subnet'
  | 'start_discovery_scan'
  | 'sync_discovery_results'
  | 'acknowledge_alert'
  | 'sync_to_netbox'
  | 'sync_all_to_netbox'
  | 'create_user'
  | 'update_user_role'
  | 'set_user_active'
  | 'reset_user_password'
  | 'delete_user';

/** Roles a user can have. Viewers can use READ tools only. */
export type AssistantRole = 'ADMIN' | 'OPERATOR' | 'VIEWER' | 'WORKER';

/**
 * SSE event sent from the backend to the frontend over the stream.
 * The frontend maps these to UI updates. Keep this list small —
 * anything the LLM produces is already covered by `text` + `tool_call`
 * + `tool_result`; only `confirmation_required` is NetConsole-specific.
 */
export type AssistantStreamEvent =
  | { type: 'session'; sessionId: string; model: string }
  | { type: 'text'; content: string }
  | {
      type: 'tool_call';
      id: string;
      name: AssistantToolName;
      arguments: Record<string, unknown>;
    }
  | {
      type: 'tool_result';
      id: string;
      name: AssistantToolName;
      ok: boolean;
      // Truncated to ~4 KB to keep the SSE pipe light. The full
      // result is still persisted to the AssistantMessage row.
      preview: unknown;
      error?: string;
    }
  | {
      type: 'confirmation_required';
      id: string;
      name: AssistantToolName;
      arguments: Record<string, unknown>;
      // Human-readable summary, e.g. "Shutdown xe-0/0/5 on LAB-F2-AS-01".
      // Generated by the backend's tool catalog so the UI never has
      // to render raw arguments.
      summary: string;
    }
  | { type: 'error'; message: string }
  | {
      type: 'usage';
      inputTokens: number;
      cachedInputTokens: number;
      outputTokens: number;
      costMicrodollars: number;
    }
  | { type: 'done' };

/** Body of POST /api/assistant. Frontend owns the conversation. */
export type AssistantRequest = {
  /** The full conversation, in OpenAI Chat Completions shape. */
  messages: AssistantMessage[];
  /**
   * The latest user message. Appended to `messages` server-side and
   * persisted before any LLM call, so even a mid-stream crash leaves
   * a complete audit trail.
   */
  userMessage: string;
  /**
   * Optional. If the user just clicked "Confirm" on a previously
   * surfaced `confirmation_required` card, the frontend echoes the
   * tool call here so the backend can execute it.
   */
  confirmedToolCall?: {
    id: string;
    name: AssistantToolName;
    arguments: Record<string, unknown>;
  };
  /**
   * Optional. Existing session to continue. If omitted the backend
   * creates a new session.
   */
  sessionId?: string;
};

/** Short preview returned by a tool executor. Truncated for SSE. */
export type ToolResult = {
  ok: boolean;
  /** Summary the LLM will see. Kept compact (< 4 KB) to save tokens.
   *  Optional because failure responses may carry only `error`. */
  preview?: unknown;
  /** When `ok = false`, the error string the LLM should know about. */
  error?: string;
};

/** Handler signature for a tool the LLM can call. */
export type ToolHandler = (
  args: Record<string, unknown>,
  context: ToolContext,
) => Promise<ToolResult>;

/** Per-request context passed to every tool handler. */
export type ToolContext = {
  userId: string | null;
  username: string | null;
  role: AssistantRole;
  sessionId: string;
};
